export const CATEGORIES = [
  // Expense categories
  { id: 'food', name: 'Food & Dining', icon: '🍔' },
  { id: 'transport', name: 'Transport', icon: '🚌' },
  { id: 'shopping', name: 'Shopping', icon: '🛍️' },
  { id: 'entertainment', name: 'Entertainment', icon: '🎬' },
  { id: 'bills', name: 'Bills & Utilities', icon: '💡' },
  { id: 'health', name: 'Health & Medical', icon: '🏥' },
  { id: 'education', name: 'Education', icon: '📚' },
  { id: 'investment', name: 'Investment', icon: '📈' },
  { id: 'travel', name: 'Travel', icon: '✈️' },
  { id: 'housing', name: 'Housing & Rent', icon: '🏠' },
  { id: 'insurance', name: 'Insurance', icon: '🛡️' },
  { id: 'clothing', name: 'Clothing', icon: '👗' },
  { id: 'subscriptions', name: 'Subscriptions', icon: '📱' },
  { id: 'pets', name: 'Pets', icon: '🐾' },
  { id: 'personal', name: 'Personal Care', icon: '💆' },

  // Income categories
  { id: 'salary', name: 'Salary', icon: '💰', defaultType: 'income' },
  { id: 'freelance', name: 'Freelance', icon: '💼', defaultType: 'income' },
  { id: 'business', name: 'Business', icon: '🏢', defaultType: 'income' },
  { id: 'rental', name: 'Rental Income', icon: '🏘️', defaultType: 'income' },
  { id: 'bonus', name: 'Bonus', icon: '🎯', defaultType: 'income' },
  { id: 'gift', name: 'Gift', icon: '🎁', defaultType: 'income' },
  { id: 'pension', name: 'Pension', icon: '🧓', defaultType: 'income' },
  { id: 'dividends', name: 'Dividends', icon: '📊', defaultType: 'income' },
  { id: 'interest', name: 'Interest', icon: '🏦', defaultType: 'income' },
  { id: 'cashback', name: 'Cashback', icon: '💳', defaultType: 'income' },
  { id: 'refund', name: 'Refund', icon: '🔄', defaultType: 'income' },
  { id: 'side_income', name: 'Side Income', icon: '💡', defaultType: 'income' },
  { id: 'government', name: 'Government Aid', icon: '🏛️', defaultType: 'income' },

  // Other
  { id: 'other', name: 'Other', icon: '📦' },
];

export const CURRENCIES = [
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  { code: 'CHF', symbol: 'Fr', name: 'Swiss Franc' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  { code: 'MXN', symbol: '$', name: 'Mexican Peso' },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound' },
];
