export type CsvTransactionType = "income" | "expense";
export type CsvImportField = "date" | "type" | "category" | "amount" | "note";
export type CsvBudgetField = "month" | "category" | "amount";

export interface CsvImportRecord {
  lineNumber: number;
  cells: string[];
}

export interface CsvImportDocument {
  records: CsvImportRecord[];
  detectedHeaderLine: number | null;
}

export interface CsvImportTable {
  headers: string[];
  rows: CsvImportRecord[];
  hasHeader: boolean;
}

export interface CsvBudgetTable {
  headers: string[];
  rows: CsvImportRecord[];
}

export interface CsvBudgetColumnMapping {
  month: number | null;
  category: number | null;
  amount: number | null;
}

export interface CsvColumnMapping {
  date: number | null;
  type: number | null;
  category: number | null;
  amount: number | null;
  note: number | null;
}

export interface CsvImportCategory {
  id: string;
  name: string;
  type: CsvTransactionType;
  isArchived?: boolean;
}

export interface CsvExistingTransaction {
  date: string;
  type: CsvTransactionType;
  amount: number;
  category: string;
  note?: string | null;
}

export interface CsvExistingBudget {
  category: string;
  amount: number;
  monthKey: string;
}

export interface CsvImportPreviewRow extends CsvImportRecord {
  date: string | null;
  type: CsvTransactionType | null;
  amount: number | null;
  sourceCategory: string;
  categoryId: string | null;
  categoryName: string;
  note: string;
  errors: string[];
  possibleDuplicate: boolean;
  duplicateReason: string | null;
}

export interface CsvBudgetPreviewRow extends CsvImportRecord {
  monthKey: string | null;
  sourceCategory: string;
  categoryId: string | null;
  categoryName: string;
  amount: number | null;
  errors: string[];
  possibleDuplicate: boolean;
  duplicateReason: string | null;
}

const HEADER_ALIASES: Record<CsvImportField, string[]> = {
  date: [
    "date",
    "transactiondate",
    "transdate",
    "postingdate",
    "valuedate",
    "txn date",
  ],
  type: [
    "type",
    "transactiontype",
    "direction",
    "incomeexpense",
    "debitcredit",
  ],
  category: ["category", "categoryname", "categoryid", "cat"],
  amount: ["amount", "transactionamount", "value", "amountusd"],
  note: ["note", "memo", "description", "details", "merchant"],
};

function normalizeHeader(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, "");
}

function isBlankRecord(record: CsvImportRecord): boolean {
  return record.cells.every((cell) => cell.trim() === "");
}

function isBudgetSection(record: CsvImportRecord): boolean {
  const nonEmptyCells = record.cells.filter((cell) => cell.trim() !== "");
  return (
    nonEmptyCells.length === 1 &&
    /^budgets?\s*(?:\(\d+\))?$/i.test(nonEmptyCells[0].trim())
  );
}

function isSectionMarker(record: CsvImportRecord): boolean {
  const nonEmptyCells = record.cells.filter((cell) => cell.trim() !== "");
  return (
    nonEmptyCells.length === 1 &&
    /^(?:transactions?|budgets?)\s*(?:\(\d+\))?$/i.test(nonEmptyCells[0].trim())
  );
}

function headerMapping(headers: string[]): CsvColumnMapping {
  const mapping: CsvColumnMapping = {
    date: null,
    type: null,
    category: null,
    amount: null,
    note: null,
  };

  for (const field of Object.keys(HEADER_ALIASES) as CsvImportField[]) {
    const aliases = new Set(HEADER_ALIASES[field].map(normalizeHeader));
    const index = headers.findIndex((header) =>
      aliases.has(normalizeHeader(header)),
    );
    if (index >= 0) mapping[field] = index;
  }
  return mapping;
}

function findHeaderRecordIndex(records: CsvImportRecord[]): number {
  let bestIndex = -1;
  let bestScore = 0;

  records.forEach((record, index) => {
    if (isBlankRecord(record) || isBudgetSection(record)) return;
    const mapped = headerMapping(record.cells);
    if (mapped.date === null || mapped.amount === null) return;
    const score = Object.values(mapped).filter(
      (value) => value !== null,
    ).length;
    if (score > bestScore) {
      bestIndex = index;
      bestScore = score;
    }
  });

  return bestIndex;
}

/**
 * Parses RFC-4180-style comma-separated text and the Excel-safe `="value"`
 * cells generated by LifeLedger's own CSV export.
 */
export function parseCsvDocument(text: string): CsvImportDocument {
  const source = text.replace(/^\uFEFF/, "");
  const records: CsvImportRecord[] = [];
  let cells: string[] = [];
  let value = "";
  let state: "start" | "unquoted" | "quoted" | "afterQuoted" = "start";
  let lineNumber = 1;
  let recordLineNumber = 1;

  const pushCell = () => {
    cells.push(value);
    value = "";
    state = "start";
  };

  const pushRecord = () => {
    pushCell();
    records.push({ lineNumber: recordLineNumber, cells });
    cells = [];
    lineNumber += 1;
    recordLineNumber = lineNumber;
  };

  for (let index = 0; index < source.length; ) {
    const char = source[index];

    if (state === "quoted") {
      if (char === '"') {
        if (source[index + 1] === '"') {
          value += '"';
          index += 2;
        } else {
          state = "afterQuoted";
          index += 1;
        }
      } else {
        value += char;
        if (char === "\n") lineNumber += 1;
        index += 1;
      }
      continue;
    }

    if (state === "afterQuoted") {
      if (char === ",") {
        pushCell();
        index += 1;
      } else if (char === "\r" || char === "\n") {
        if (char === "\r" && source[index + 1] === "\n") index += 1;
        pushRecord();
        index += 1;
      } else if (/\s/.test(char)) {
        index += 1;
      } else {
        value += char;
        state = "unquoted";
        index += 1;
      }
      continue;
    }

    if (state === "start") {
      if (char === ",") {
        pushCell();
        index += 1;
      } else if (char === "\r" || char === "\n") {
        if (char === "\r" && source[index + 1] === "\n") index += 1;
        pushRecord();
        index += 1;
      } else if (char === '"') {
        state = "quoted";
        index += 1;
      } else if (char === "=" && source[index + 1] === '"') {
        // LifeLedger wraps short text cells this way to protect spreadsheet apps.
        state = "quoted";
        index += 2;
      } else {
        value += char;
        state = "unquoted";
        index += 1;
      }
      continue;
    }

    if (char === ",") {
      pushCell();
      index += 1;
    } else if (char === "\r" || char === "\n") {
      if (char === "\r" && source[index + 1] === "\n") index += 1;
      pushRecord();
      index += 1;
    } else {
      value += char;
      index += 1;
    }
  }

  if (value.length > 0 || cells.length > 0 || state !== "start") {
    pushCell();
    records.push({ lineNumber: recordLineNumber, cells });
  }

  return {
    records,
    detectedHeaderLine:
      records[findHeaderRecordIndex(records)]?.lineNumber ?? null,
  };
}

export function buildTransactionTable(
  document: CsvImportDocument,
  firstRowIsHeader = true,
): CsvImportTable {
  const nonBlankRecords = document.records.filter(
    (record) => !isBlankRecord(record),
  );
  if (nonBlankRecords.length === 0) {
    return { headers: [], rows: [], hasHeader: false };
  }

  const detectedIndex =
    document.detectedHeaderLine === null
      ? -1
      : document.records.findIndex(
          (record) => record.lineNumber === document.detectedHeaderLine,
        );
  const firstIndex = document.records.findIndex(
    (record) => !isBlankRecord(record),
  );
  const headerIndex =
    firstRowIsHeader && detectedIndex >= 0 ? detectedIndex : firstIndex;
  const hasHeader = firstRowIsHeader;
  const headers = hasHeader
    ? document.records[headerIndex].cells.map(
        (cell, index) => cell.trim() || `Column ${index + 1}`,
      )
    : Array.from(
        {
          length: Math.max(
            ...nonBlankRecords.map((record) => record.cells.length),
          ),
        },
        (_, index) => `Column ${index + 1}`,
      );
  const dataStartIndex = hasHeader ? headerIndex + 1 : firstIndex;
  const rows: CsvImportRecord[] = [];

  for (const record of document.records.slice(dataStartIndex)) {
    if (isBudgetSection(record)) break;
    if (!isBlankRecord(record)) rows.push(record);
  }

  return { headers, rows, hasHeader };
}

export function guessBudgetColumnMapping(
  headers: string[],
): CsvBudgetColumnMapping {
  const normalized = headers.map(normalizeHeader);
  const findIndex = (aliases: string[]) => {
    const index = normalized.findIndex((header) =>
      aliases.some((alias) => normalizeHeader(alias) === header),
    );
    return index < 0 ? null : index;
  };
  return {
    month: findIndex(["month", "monthkey", "budgetmonth", "period", "cycle"]),
    category: findIndex([
      "category",
      "categoryname",
      "categoryid",
      "group",
      "envelope",
    ]),
    amount: findIndex([
      "limit",
      "budget",
      "budgetamount",
      "monthlylimit",
      "monthlybudget",
      "monthlyamount",
      "budgetlimit",
      "limitamount",
      "amount",
      "plannedamount",
      "allocation",
    ]),
  };
}

/**
 * Finds a Budgets section in a LifeLedger export, or recognizes a standalone
 * budget CSV using Month, Category, and Limit/Budget/Amount columns.
 */
export function buildBudgetTable(document: CsvImportDocument): CsvBudgetTable {
  let headerIndex = -1;
  const budgetSectionIndex = document.records.findIndex(isBudgetSection);

  document.records.forEach((record, index) => {
    if (budgetSectionIndex >= 0 && index <= budgetSectionIndex) return;
    if (isBlankRecord(record) || isSectionMarker(record)) return;
    const candidate = guessBudgetColumnMapping(record.cells);
    if (
      candidate.month !== null &&
      candidate.category !== null &&
      candidate.amount !== null
    ) {
      headerIndex = index;
    }
  });

  // A LifeLedger export labels its budget section explicitly, so its first
  // nonblank row is the budget header even when the column names are custom.
  if (headerIndex < 0 && budgetSectionIndex >= 0) {
    headerIndex = document.records.findIndex(
      (record, index) => index > budgetSectionIndex && !isBlankRecord(record),
    );
  }

  if (headerIndex < 0) {
    return { headers: [], rows: [] };
  }

  const headers = document.records[headerIndex].cells.map(
    (cell, index) => cell.trim() || `Column ${index + 1}`,
  );
  const rows: CsvImportRecord[] = [];
  for (const record of document.records.slice(headerIndex + 1)) {
    if (isSectionMarker(record)) break;
    if (!isBlankRecord(record)) rows.push(record);
  }

  return { headers, rows };
}

export function guessTransactionColumnMapping(
  headers: string[],
): CsvColumnMapping {
  return headerMapping(headers);
}

export function categoryMappingKey(
  type: CsvTransactionType,
  sourceCategory: string,
): string {
  return `${type}:${sourceCategory.trim().toLowerCase().replace(/\s+/g, " ")}`;
}

function parseTransactionType(value: string): CsvTransactionType | null {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[\s_-]+/g, "");
  if (["income", "credit", "deposit", "moneyin", "in"].includes(normalized)) {
    return "income";
  }
  if (
    ["expense", "debit", "withdrawal", "moneyout", "out", "payment"].includes(
      normalized,
    )
  ) {
    return "expense";
  }
  return null;
}

function parseAmount(value: string): { amount: number; sign: number } | null {
  let normalized = value.trim();
  if (!normalized) return null;

  const parenthesizedNegative = /^\(.*\)$/.test(normalized);
  normalized = normalized.replace(/^\((.*)\)$/, "$1");
  normalized = normalized
    .replace(/^[A-Z]{3}\s*/i, "")
    .replace(/[$€£¥₹\s]/g, "");

  const explicitNegative = normalized.startsWith("-");
  normalized = normalized.replace(/^[+-]/, "");

  if (normalized.includes(",") && !normalized.includes(".")) {
    if (/^\d{1,3}(,\d{3})+$/.test(normalized)) {
      normalized = normalized.replace(/,/g, "");
    } else {
      // A decimal comma is ambiguous across locales; never silently change it.
      return null;
    }
  } else {
    normalized = normalized.replace(/,/g, "");
  }

  if (!/^(?:\d+(?:\.\d*)?|\.\d+)$/.test(normalized)) return null;
  const amount = Number(normalized);
  if (!Number.isFinite(amount)) return null;
  return {
    amount: Math.abs(amount),
    sign: parenthesizedNegative || explicitNegative ? -1 : 1,
  };
}

function parseDate(value: string): string | null {
  const normalized = value.trim();
  const iso = normalized.match(/^(\d{4})-(\d{2})-(\d{2})(?:$|T)/);
  const us = normalized.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  const match = iso ?? us;
  if (!match) return null;

  const year = Number(iso ? match[1] : match[3]);
  const month = Number(iso ? match[2] : match[1]);
  const day = Number(iso ? match[3] : match[2]);
  const date = new Date(Date.UTC(year, month - 1, day));
  if (
    date.getUTCFullYear() !== year ||
    date.getUTCMonth() !== month - 1 ||
    date.getUTCDate() !== day
  ) {
    return null;
  }
  return `${String(year).padStart(4, "0")}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
}

function parseBudgetMonth(value: string): string | null {
  const normalized = value.trim();
  const numeric = normalized.match(
    /^(\d{4})-(\d{1,2})(?:-\d{1,2})?$|^(\d{1,2})[/-](\d{4})$/,
  );
  if (numeric) {
    const year = Number(numeric[1] ?? numeric[4]);
    const month = Number(numeric[2] ?? numeric[3]);
    if (month < 1 || month > 12) return null;
    return `${String(year).padStart(4, "0")}-${String(month).padStart(2, "0")}`;
  }

  const named = normalized.match(
    /^([a-z]+)[\s,/-]+(\d{4})$|^(\d{4})[\s,/-]+([a-z]+)$/i,
  );
  if (!named) return null;
  const monthName = (named[1] ?? named[4]).toLowerCase();
  const year = Number(named[2] ?? named[3]);
  const monthNames = [
    ["january", "jan"],
    ["february", "feb"],
    ["march", "mar"],
    ["april", "apr"],
    ["may"],
    ["june", "jun"],
    ["july", "jul"],
    ["august", "aug"],
    ["september", "sep", "sept"],
    ["october", "oct"],
    ["november", "nov"],
    ["december", "dec"],
  ];
  const monthIndex = monthNames.findIndex((aliases) =>
    aliases.includes(monthName),
  );
  if (monthIndex < 0) return null;
  return `${String(year).padStart(4, "0")}-${String(monthIndex + 1).padStart(2, "0")}`;
}

function amountToMinorUnits(amount: number): number {
  return Math.round(amount * 100);
}

function duplicateKey(
  row: Pick<CsvImportPreviewRow, "date" | "type" | "amount" | "categoryId">,
): string | null {
  if (!row.date || !row.type || row.amount === null || !row.categoryId) {
    return null;
  }
  return JSON.stringify([
    row.date,
    row.type,
    amountToMinorUnits(row.amount),
    row.categoryId,
  ]);
}

export function buildTransactionPreview(
  table: CsvImportTable,
  mapping: CsvColumnMapping,
  categories: CsvImportCategory[],
  existingTransactions: CsvExistingTransaction[],
  categoryMappings: Record<string, string> = {},
): CsvImportPreviewRow[] {
  const activeCategories = categories.filter(
    (category) => !category.isArchived,
  );
  const getCell = (record: CsvImportRecord, index: number | null) =>
    index === null ? "" : (record.cells[index] ?? "").trim();

  const previewRows = table.rows.map((record): CsvImportPreviewRow => {
    const errors: string[] = [];
    const dateValue = getCell(record, mapping.date);
    const parsedDate = dateValue ? parseDate(dateValue) : null;
    if (mapping.date === null) errors.push("Map a column to Date.");
    else if (!parsedDate)
      errors.push("Use a valid date (YYYY-MM-DD or MM/DD/YYYY).");

    const amountValue = getCell(record, mapping.amount);
    const parsedAmount =
      mapping.amount === null ? null : parseAmount(amountValue);
    if (mapping.amount === null) errors.push("Map a column to Amount.");
    else if (!parsedAmount || parsedAmount.amount <= 0) {
      errors.push("Enter a valid amount greater than zero.");
    }

    const rawType = getCell(record, mapping.type);
    let type = rawType ? parseTransactionType(rawType) : null;
    if (mapping.type !== null && rawType && !type) {
      errors.push("Use Income or Expense for transaction type.");
    }
    if (!type && (mapping.type === null || !rawType) && parsedAmount) {
      type = parsedAmount.sign < 0 ? "expense" : null;
    }
    if (!type && !errors.some((error) => error.includes("transaction type"))) {
      errors.push("Map a Type column or use negative amounts for expenses.");
    }

    const sourceCategory = getCell(record, mapping.category);
    if (mapping.category === null) errors.push("Map a column to Category.");
    else if (!sourceCategory) errors.push("Category is required.");

    let categoryId: string | null = null;
    let categoryName = sourceCategory;
    if (sourceCategory && type) {
      const manualId =
        categoryMappings[categoryMappingKey(type, sourceCategory)];
      const manuallySelected = manualId
        ? activeCategories.find(
            (category) => category.id === manualId && category.type === type,
          )
        : undefined;
      const directMatch = activeCategories.find(
        (category) =>
          category.type === type &&
          (category.id === sourceCategory ||
            categoryMappingKey(type, category.name) ===
              categoryMappingKey(type, sourceCategory)),
      );
      const matchedCategory = manuallySelected ?? directMatch;
      if (matchedCategory) {
        categoryId = matchedCategory.id;
        categoryName = matchedCategory.name;
      } else {
        errors.push(`Map "${sourceCategory}" to an active ${type} category.`);
      }
    }

    return {
      ...record,
      date: parsedDate,
      type,
      amount: parsedAmount?.amount ?? null,
      sourceCategory,
      categoryId,
      categoryName,
      note: getCell(record, mapping.note),
      errors,
      possibleDuplicate: false,
      duplicateReason: null,
    };
  });

  const existingKeys = new Set(
    existingTransactions.map((transaction) =>
      duplicateKey({
        date: parseDate(transaction.date) ?? transaction.date.slice(0, 10),
        type: transaction.type,
        amount: transaction.amount,
        categoryId: transaction.category,
      }),
    ),
  );
  const seenImportKeys = new Set<string>();

  for (const row of previewRows) {
    if (row.errors.length > 0) continue;
    const key = duplicateKey(row);
    if (!key) continue;

    if (existingKeys.has(key)) {
      row.possibleDuplicate = true;
      row.duplicateReason = "Matches an existing transaction.";
    } else if (seenImportKeys.has(key)) {
      row.possibleDuplicate = true;
      row.duplicateReason = "Matches another row in this CSV.";
    }
    seenImportKeys.add(key);
  }

  return previewRows;
}

function budgetDuplicateKey(
  budget: Pick<CsvBudgetPreviewRow, "monthKey" | "categoryId">,
): string | null {
  if (!budget.monthKey || !budget.categoryId) return null;
  return JSON.stringify([budget.monthKey, budget.categoryId]);
}

export function buildBudgetPreview(
  table: CsvBudgetTable,
  mapping: CsvBudgetColumnMapping,
  categories: CsvImportCategory[],
  existingBudgets: CsvExistingBudget[],
  categoryMappings: Record<string, string> = {},
): CsvBudgetPreviewRow[] {
  const activeCategories = categories.filter(
    (category) => !category.isArchived && category.type === "expense",
  );
  const getCell = (record: CsvImportRecord, index: number | null) =>
    index === null ? "" : (record.cells[index] ?? "").trim();

  const rows = table.rows.map((record): CsvBudgetPreviewRow => {
    const errors: string[] = [];
    const rawMonth =
      mapping.month === null ? "" : getCell(record, mapping.month);
    const monthKey = rawMonth ? parseBudgetMonth(rawMonth) : null;
    if (mapping.month === null) errors.push("Map a column to Month.");
    else if (!monthKey) {
      errors.push("Use a valid budget month, such as January 2025 or 2025-01.");
    }

    const sourceCategory =
      mapping.category === null ? "" : getCell(record, mapping.category);
    if (mapping.category === null) errors.push("Map a column to Category.");
    else if (!sourceCategory) errors.push("Category is required.");

    const rawAmount =
      mapping.amount === null ? "" : getCell(record, mapping.amount);
    const parsedAmount =
      mapping.amount === null ? null : parseAmount(rawAmount);
    if (mapping.amount === null) errors.push("Map a column to Limit.");
    else if (!parsedAmount || parsedAmount.amount <= 0) {
      errors.push("Enter a valid budget limit greater than zero.");
    }

    let categoryId: string | null = null;
    let categoryName = sourceCategory;
    if (sourceCategory) {
      const manualId =
        categoryMappings[categoryMappingKey("expense", sourceCategory)];
      const manuallySelected = manualId
        ? activeCategories.find((category) => category.id === manualId)
        : undefined;
      const directMatch = activeCategories.find(
        (category) =>
          category.id === sourceCategory ||
          categoryMappingKey("expense", category.name) ===
            categoryMappingKey("expense", sourceCategory),
      );
      const matchedCategory = manuallySelected ?? directMatch;
      if (matchedCategory) {
        categoryId = matchedCategory.id;
        categoryName = matchedCategory.name;
      } else {
        errors.push(`Map "${sourceCategory}" to an active expense category.`);
      }
    }

    return {
      ...record,
      monthKey,
      sourceCategory,
      categoryId,
      categoryName,
      amount: parsedAmount?.amount ?? null,
      errors,
      possibleDuplicate: false,
      duplicateReason: null,
    };
  });

  const existingKeys = new Set(
    existingBudgets.map((budget) =>
      budgetDuplicateKey({
        monthKey: budget.monthKey,
        categoryId: budget.category,
      }),
    ),
  );
  const seenImportKeys = new Set<string>();

  for (const row of rows) {
    if (row.errors.length > 0) continue;
    const key = budgetDuplicateKey(row);
    if (!key) continue;
    if (existingKeys.has(key)) {
      row.possibleDuplicate = true;
      row.duplicateReason =
        "A budget already exists for this category and month; importing will update its limit.";
    } else if (seenImportKeys.has(key)) {
      row.possibleDuplicate = true;
      row.duplicateReason =
        "Another row in this CSV uses the same category and month.";
    }
    seenImportKeys.add(key);
  }

  return rows;
}