export const DEFAULT_CATEGORIES = [
  { id: "food", name: "Food & Dining", icon: "🍔", type: "expense" },
  { id: "transport", name: "Transport", icon: "🚌", type: "expense" },
  { id: "shopping", name: "Shopping", icon: "🛍️", type: "expense" },
  { id: "entertainment", name: "Entertainment", icon: "🎬", type: "expense" },
  { id: "bills", name: "Bills & Utilities", icon: "💡", type: "expense" },
  { id: "health", name: "Health & Medical", icon: "🏥", type: "expense" },
  { id: "education", name: "Education", icon: "📚", type: "expense" },
  { id: "investment", name: "Investment", icon: "📈", type: "expense" },
  { id: "travel", name: "Travel", icon: "✈️", type: "expense" },
  { id: "housing", name: "Housing & Rent", icon: "🏠", type: "expense" },
  { id: "insurance", name: "Insurance", icon: "🛡️", type: "expense" },
  { id: "clothing", name: "Clothing", icon: "👗", type: "expense" },
  { id: "subscriptions", name: "Subscriptions", icon: "📱", type: "expense" },
  { id: "pets", name: "Pets", icon: "🐾", type: "expense" },
  { id: "personal", name: "Personal Care", icon: "💆", type: "expense" },
  { id: "other", name: "Other", icon: "📦", type: "expense" },
  { id: "salary", name: "Salary", icon: "💰", type: "income" },
  { id: "freelance", name: "Freelance", icon: "💼", type: "income" },
  { id: "business", name: "Business", icon: "🏢", type: "income" },
  { id: "rental", name: "Rental Income", icon: "🏘️", type: "income" },
  { id: "bonus", name: "Bonus", icon: "🎯", type: "income" },
  { id: "gift", name: "Gift", icon: "🎁", type: "income" },
  { id: "pension", name: "Pension", icon: "🧓", type: "income" },
  { id: "dividends", name: "Dividends", icon: "📊", type: "income" },
  { id: "interest", name: "Interest", icon: "🏦", type: "income" },
  { id: "cashback", name: "Cashback", icon: "💳", type: "income" },
  { id: "refund", name: "Refund", icon: "🔄", type: "income" },
  { id: "side_income", name: "Side Income", icon: "💡", type: "income" },
  { id: "government", name: "Government Aid", icon: "🏛️", type: "income" },
] as const;